export const industrySeeder = [
  "Accounting",
  "Agriculture",
  "Automobile",
  "Beauty & Cosmetics",
  "Broadcasting",
  "Cleaning/Laundry",
  "Computer Engineering",
  "Construction",
  "Creative Arts",
  "E-commerce",
  "Education",
  "Electronics",
  "Energy",
  "Engineering",
  "Entertainment",
  "Events",
  "Fashion & Apparel",
  "Finance",
  "Food & Drinks",
  "Government",
  "Healthcare",
  "Hospitality",
  "HR/Recruitment",
  "Insurance",
  "Interior Design",
  "Jewelry & Accessories",
  "Legal",
  "Manufacturing",
  "Marketing",
  "Ministry/NGO",
  "Multimedia",
  "Printing & Publishing",
  "Real Estate",
  "Retail",
  "Transport/Logistics",
  "Security",
  "Social Media",
  "Information Technology",
  "Travel",
  "Telecommunications",
  "Wellness & Fitness",
  "Wholesale",
];
