import type { Metadata } from "next";
import { Raleway, Poppins, Montserrat } from "next/font/google";
import clsx from "clsx";
// 
import "@/styles/globals.css";

const fontPoppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const fontMontserrat = Montserrat({
  variable: "--font-Montserrat",
  subsets: ["latin"],
  display: "swap",
});

const fontRaleway = Raleway({
  variable: "--font-Raleway",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={clsx(
          fontPoppins.variable,
          fontMontserrat.variable,
          fontRaleway.variable,
          "antialiased font-[Poppins]"
        )}
      >
        {children}
      </body>
    </html>
  );
}
